basePath: /
host: localhost:8080
info:
  contact:
    email: lumoshive.academy@gmail.com
    name: API Support
    url: https://academy.lumoshive.com/contact-us
  description: This is a sample server for a Swagger API.
  license:
    name: Lumoshive Academy
    url: https://academy.lumoshive.com
  termsOfService: http://example.com/terms/
  title: Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user with their username and passwor.
      produces:
      - application/json
      responses: {}
      summary: Login user
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  BasixAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
